<?php

/**
 *  ____        _ _    ___  ____    _  _    ___
 * / ___|  __ _| | |_ / _ \/ ___|  | || |  / _ \
 * \___ \ / _` | | __| | | \___ \  | || |_| | | |
 *  ___) | (_| | | |_| |_| |___) | |__   _| |_| |
 * |____/ \__,_|_|\__|\___/|____/     |_|(_)___/
 *
 * SaltOS: Framework to develop Rich Internet Applications
 * Copyright (c) 2007-2026 Josep Sanz Campderrós
 * SPDX-License-Identifier: MIT
 * Licensed under the MIT License.
 * See the LICENSE file in the project root for full license information.
 */

declare(strict_types=1);

/**
 * Make indexing action
 *
 * This fie contains useful functions related to the indexing action that internally uses the
 * mroonga engine to search in the fulltext string generated by this action
 */

if (!get_data('server/xuid')) {
    show_php_error(['phperror' => 'Permission denied']);
}

if (!semaphore_acquire('indexing')) {
    show_php_error(['phperror' => 'Could not acquire the semaphore']);
}

db_connect();
require_once 'php/lib/unoconv.php';
require_once 'php/lib/indexing.php';
$time1 = microtime(true);
$total1 = indexing_files();
$time2 = microtime(true);
$total2 = indexing_apps();
$time3 = microtime(true);

semaphore_release('indexing');
output_handler_json([
    'indexing_files' => [
        'time' => round($time2 - $time1, 6),
        'total' => $total1,
    ],
    'indexing_apps' => [
        'time' => round($time3 - $time2, 6),
        'total' => $total2,
    ],
]);
