services:

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: mssql2022
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "asd123ASD"
        ports:
            - "0.0.0.0:1433:1433"
        volumes:
            - ../volumes/test/mssql:/var/opt/mssql
        profiles: ["test"]
        restart: unless-stopped

    postgres:
        image: postgres:17
        container_name: pgsql17
        environment:
            POSTGRES_PASSWORD: saltos
            POSTGRES_USER: saltos
            POSTGRES_DB: saltos
        ports:
            - "0.0.0.0:5432:5432"
        volumes:
            - ../volumes/test/postgres:/var/lib/postgresql/data
        profiles: ["test"]
        restart: unless-stopped

    greenmail:
        image: greenmail/standalone:latest
        container_name: greenmail
        environment:
            GREENMAIL_OPTS: >
                -Dgreenmail.smtp.hostname=0.0.0.0
                -Dgreenmail.smtp.port=587
                -Dgreenmail.pop3.hostname=0.0.0.0
                -Dgreenmail.pop3.port=995
                -Dgreenmail.users=admin:admin@example.com
                -Dgreenmail.hostname=example.com
                -Dgreenmail.api.disabled=true
                -Dgreenmail.verbose
            JAVA_OPTS: -Djava.net.preferIPv4Stack=true
        ports:
            - "0.0.0.0:995:995"
            - "0.0.0.0:587:587"
        profiles: ["test"]
        restart: unless-stopped

    saltos4server:
        build:
            context: .
            dockerfile: Dockerfile.server
        container_name: saltos4server
        ports:
            - "0.0.0.0:8080:80"
            - "0.0.0.0:8443:443"
        volumes:
            - ../volumes/server/mysql:/var/lib/mysql
            - ../volumes/server/data:/opt/saltos4/instance/data
        profiles: ["server"]
        restart: unless-stopped

    saltos4devel:
        build:
            context: .
            dockerfile: Dockerfile.devel
        container_name: saltos4devel
        ports:
            - "0.0.0.0:8080:8080"
        volumes:
            - ../volumes/devel/data:/opt/saltos4/instance/data
        profiles: ["devel"]
        restart: unless-stopped
