
ARG PHP_VERSION=8.5

####################################################################################################
# default builder
####################################################################################################

FROM debian:trixie

ARG PHP_VERSION

RUN echo 'path-exclude /usr/share/doc/*' > /etc/dpkg/dpkg.cfg.d/01_nodoc && \
    echo 'path-exclude /usr/share/man/*' >> /etc/dpkg/dpkg.cfg.d/01_nodoc && \
    echo 'path-exclude /usr/share/locale/*' >> /etc/dpkg/dpkg.cfg.d/01_nodoc && \
    echo 'APT::Install-Recommends "false";' > /etc/apt/apt.conf.d/00_nofilters && \
    echo 'APT::Install-Suggests "false";' >> /etc/apt/apt.conf.d/00_nofilters

RUN apt update && apt install -y \
    extrepo \
    wget \
    vim \
    net-tools \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

RUN extrepo enable sury

# php
RUN apt update && apt install -y \
    php${PHP_VERSION}-bcmath \
    php${PHP_VERSION}-cli \
    php${PHP_VERSION}-common \
    php${PHP_VERSION}-curl \
    php${PHP_VERSION}-gd \
    php${PHP_VERSION}-imap \
    php${PHP_VERSION}-mailparse \
    php${PHP_VERSION}-mbstring \
    php${PHP_VERSION}-mysql \
    php${PHP_VERSION}-readline \
    php${PHP_VERSION}-sqlite3 \
    php${PHP_VERSION}-xml \
    php${PHP_VERSION}-yaml \
    php${PHP_VERSION}-zip \
    php${PHP_VERSION}-zstd \
    && rm -rf /var/lib/apt/lists/*

# pdf tools & certutils
RUN apt update && apt install -y \
    poppler-utils \
    libnss3-tools \
    && rm -rf /var/lib/apt/lists/*

# saltos4 codebase
COPY code /opt/saltos4/code
COPY scripts /opt/saltos4/scripts
COPY .git /opt/saltos4/.git

# instance setup
RUN cd /opt/saltos4 \
    && mkdir instance \
    && cd instance \
    && bash /opt/saltos4/scripts/make_instance.sh \
    && echo '<root><db><type>pdo_sqlite</type></db></root>' > data/files/config.xml \
    && mv data data-seed \
    && mkdir data \
    && mkdir wait \
    && cd wait \
    && ln -s /opt/saltos4/scripts/wait_index.html index.html

# entrypoint: populate an empty volume from the seed data, then start the server
RUN cat <<'EOF' > /usr/local/bin/docker-entrypoint.sh && chmod +x /usr/local/bin/docker-entrypoint.sh
#!/bin/bash
set -e

if [ -z "$(ls -A /opt/saltos4/instance/data)" ]; then
    php -S 0.0.0.0:8080 -t /opt/saltos4/instance/wait &
    WAIT_PID=$!

    cp -a /opt/saltos4/instance/data-seed/. /opt/saltos4/instance/data/

    php /opt/saltos4/instance/api/index.php setup
    user=admin php /opt/saltos4/instance/api/index.php setup/certs
    user=admin php /opt/saltos4/instance/api/index.php setup/company
    user=admin php /opt/saltos4/instance/api/index.php setup/emails
    user=admin php /opt/saltos4/instance/api/index.php setup/crm
    user=admin php /opt/saltos4/instance/api/index.php setup/hr
    user=admin php /opt/saltos4/instance/api/index.php setup/purchases
    user=admin php /opt/saltos4/instance/api/index.php setup/sales

    kill "$WAIT_PID" || true
    wait "$WAIT_PID" || true
fi

exec /usr/bin/php -S 0.0.0.0:8080 -t /opt/saltos4/instance/web/
EOF

CMD ["/usr/local/bin/docker-entrypoint.sh"]
