#  ____        _ _    ___  ____    _  _    ___
# / ___|  __ _| | |_ / _ \/ ___|  | || |  / _ \
# \___ \ / _` | | __| | | \___ \  | || |_| | | |
#  ___) | (_| | | |_| |_| |___) | |__   _| |_| |
# |____/ \__,_|_|\__|\___/|____/     |_|(_)___/
#
# SaltOS: Framework to develop Rich Internet Applications
# Copyright (C) 2007-2025 by Josep Sanz Campderrós
# More information in https://www.saltos.org or info@saltos.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

app: products
require: apps/common/php/default.php
template: apps/common/xml/default.xml
indent: true
screen: type5
col_class: col-md-6 mb-3
dropdown: true
list:
    # [id, type, label]
    - [name, text, Name]
    - [code, text, Code]
    - [description, text, Description]
form:
    # [id, type, label]
    - [active, switch, Active]
    - newline
    - [name, text, Name]
    - [code, text, Code]
    - [type_id, select, Type]
    - [price, float, Price]
    - [cost, float, Cost]
    - [margin, float, Margin]
    - [tax_id, select, Tax]
    - [description, textarea, Description]
    - [category_id, select, Category]
    - [unit, text, Measure unit]
    - [brand, text, Brand]
    - [model, text, Model]
    - [barcode, text, Barcode]
    - [stock, float, Stock]
    - [stock_min, float, Min stock]
    - [stock_max, float, Max stock]
    - [location, text, Location]
    - [image_url, text, Image Url]
select:
    # [id, table, optional field]
    - [tax_id, app_taxes]
    - [type_id, app_products_types]
    - [category_id, app_products_categories]
attr:
    # field:
    #     attr: value
    name:
        required: true
        autofocus: true
    code:
        required: true
        col_class: col-md-3 mb-3
    price:
        col_class: col-md-3 mb-3
    tax_id:
        col_class: col-md-3 mb-3
    type_id:
        col_class: col-md-3 mb-3
    description:
        required: true
        col_class: col-md-12 mb-3
        height: 5em
    unit:
        col_class: col-md-3 mb-3
    cost:
        col_class: col-md-3 mb-3
    margin:
        col_class: col-md-3 mb-3
    barcode:
        col_class: col-md-3 mb-3
    category_id:
        col_class: col-md-3 mb-3
    brand:
        col_class: col-md-3 mb-3
    model:
        col_class: col-md-3 mb-3
    stock:
        col_class: col-md-3 mb-3
    stock_min:
        col_class: col-md-3 mb-3
    stock_max:
        col_class: col-md-3 mb-3
